Feature/agent card
isdi-coders-2023/TortugasVeloces-202304-bcn pull request #4
Opened 2023-05-01 20:48 UTC by Arii343

2023-05-01 20:56 UTC, nilserratio requested changes
Tenemos que hacer los Test y el tema de los botones que serán un componente en sí.

2023-05-03 07:09 UTC, nilserratio requested changes
Tenemos que cambiar el nombre de los styles y unificar-los. Porque en coverage los estilos no entran.

2023-05-03 08:51 UTC, leticiaavacamathe approved these changes
🎉

2023-05-03 10:20 UTC, nilserratio approved these changes
now all ok!

2023-05-03 10:21 UTC, merged